---
title: "Survey"
date: "February 21, 2019"
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pkgs <- c("readxl" )
lapply(pkgs, function(x) if (!require(x, character.only=T)){install.packages(x);library(x, character.only = T)})


```

```{r prep_data, include = FALSE}
questions <- read_xlsx("questions.xlsx")
```

```{r, warning=FALSE, comment="", echo=FALSE, include=FALSE}


# Split data frame by sections and sort within sections
sections <- grep( "999", questions$order)
sections <- c(sections, nrow(questions))
questions$order <- as.numeric(questions$order)
sectioned_df <- lapply(1:(length(sections)-1), function(i){
  
 start <- sections[i] + 1
 end   <- sections[i+1] - 1
 df <- questions[start:end,]
 rbind(questions[start - 1,], df[order( df$order),])
})

# Questionnaire
text <- lapply(sectioned_df, function(df){
c(sapply(1:nrow(df), function(r){
  resp_options <- unlist(strsplit(df$Response_options[r], ";"))
  if(is.na(resp_options[1])) resp_options <- "\n [no options given yet]"
  
  title <- paste0("\n",df$sections[r],  
" <a id=q",r,">",df$Question_wording[r], " </a> \n ")
  stringout <- capture.output( cat(title, resp_options, sep = "\n"))
if (df$order[r] == "999") {
  resp_options <- "\n "
  title <- paste0("\n",df$sections[r], " ",df$Question_wording[r],"\n ")
  stringout <- capture.output( cat(title, resp_options, sep = "\n"))
  
  
}
  stringout 
}
))})
text <- unlist(text)

# Roles
roles <- unique(c(questions$Role,questions$Role_2) )
roles <- roles[!is.na(roles)]

ind <- sapply(roles, function(i) {

  role_1 <- which(questions$Role == i)
  role_2 <- which(questions$Role_2== i)
  c(role_1, role_2)}
  )
names(ind) <- roles

roles <- sapply(1:length(ind), function(x){
  
  
title <- paste0("\n  
## " ,names(ind)[x], " \n ")

stub <- questions$stub[ind[[x]]]
link <- paste0("q", ind[[x]])
lists <- paste0("[",stub,"](#",link,")", collapse = "\n
") 

stringout <- capture.output(cat(title, lists))
stringout 
})

roles <- unlist(roles)

```


```{r,include=FALSE}
  file.create("02 survey_questionnaire.Rmd")
  cat("# Questionnaire",
      text,
      "\n# Roles",
      roles,
      sep = "\n",
      file =  "02 survey_questionnaire.Rmd")
```


```{r questionnaire, child = "02 survey_questionnaire.Rmd"}
```

